[tool.bumpversion]
current_version = "0.1.0"
commit = true
message = "Release v{new_version}"
tag = true
tag_name = "v{new_version}"

[[tool.bumpversion.files]]
filename = "src/pishock/__init__.py"
search = "__version__ = \"{current_version}\""
replace = "__version__ = \"{new_version}\""

[[tool.bumpversion.files]]
filename = "pyproject.toml"
search = "version = \"{current_version}\""
replace = "version = \"{new_version}\""
