[tool.poetry]
name = "pishock"
version = "0.1.0"
description = ""
authors = ["Zerario <derg@zerario.dev>"]
readme = "README.md"
packages = [{include = "pishock", from = "src"}]

[tool.poetry.dependencies]
python = ">=3.8, <=3.12"
requests = "^2.31.0"
typer = "^0.9.0"
rich = "^13.5.2"
typing-extensions = {version = "^4.7.1", python = "<3.9"}

[tool.poetry.scripts]
pishock = "pishock.cli:app"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
