name: main
on: [push, pull_request]
env:
  FORCE_COLOR: "1"
  PY_COLORS: "1"

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10", "3.11", "3.12"]
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - run: pip install tox
      - run: tox -e py

  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env: [check-format, mypy]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: pip install tox
      - run: tox -e ${{ matrix.env }}

  package:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build package
      uses: hynek/build-and-inspect-python-package@v2

  deploy:
    if: github.event_name == 'push' && startsWith(github.event.ref, 'refs/tags')
    runs-on: ubuntu-latest
    needs: [tests, lint, package]
    environment:
      name: pypi
      url: https://pypi.org/p/pishock
    permissions:
      id-token: write  # for trusted publishing
    steps:
    - name: Download package
      uses: actions/download-artifact@v4
      with:
        name: Packages
        path: dist
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@release/v1
